### ISSUE TITLE
Status of fcc tracking

### ISSUE THREAD

**Issue by georgezee** [achernyak/fcc-tracker#12]
Am I correct in saying that this tracking app would've been broken by the 2018 update to freecodecamp?

I can login to the dashboard at http://freecodecamp-tracker.achernyak.me, but the progress column is just stuck at "Loading ..." for the user that I added.

Is this expected to still be working?

**Comment by hackeryarn** [comment]
You are correct. The update broke the data pull. I stopped teaching the class I was using this for, so I didn't not notice the issue.

Thanks for the report! I will get this updated.

**Comment by hackeryarn** [comment]
Looks like FreeCodeCamp started using React which prevents any web scraping. I have deprecated the project, but will keep it around as an example of a full stack Clojure project.
