### ISSUE TITLE
Add search to members table

### ISSUE THREAD

**Issue by hackeryarn** [achernyak/fcc-tracker#4]

**Comment by coryellcp** [comment]
So does this have to be done from scratch, or is clojure like rails where's a gem we can use?

**Comment by hackeryarn** [comment]
You do have access to libraries, but this may be easier from scratch. I would Google around, also most react libraries should work.

**Comment by hackeryarn** [comment]
https://github.com/Yomguithereal/clj-fuzzy take a look at this for the search algorithm itself. Then you can implement the text box around it.

**Comment by hackeryarn** [comment]
Deprecated.
